from __future__ import annotations

from pathlib import Path
from typing import Any

from .validation import load_manifest


def generate_markdown_integration(manifest_path: str | Path, output_path: str | Path | None = None) -> str:
    manifest = load_manifest(manifest_path)
    name = manifest["name"]
    version = manifest["version"]
    description = manifest.get("description", "")
    runtime = manifest["runtime"]
    entry = manifest["entry"]
    triggers = manifest.get("triggers", {})
    capabilities = manifest.get("capabilities", [])
    config_section = manifest.get("config", {})
    deps = manifest.get("dependencies", {})
    perms = manifest.get("permissions", [])
    skill_id = manifest.get("id", "")
    lifecycle = manifest.get("lifecycle", {})

    md = f"""# {name} v{version}

> {description}

**Skill ID:** `{skill_id}`
**Runtime:** {runtime}
**Entry Point:** {entry}

---

## Triggers

"""

    events = triggers.get("events", [])
    commands = triggers.get("commands", [])

    if events:
        md += "### Events\n\n"
        for ev in events:
            md += f"- `{ev}`\n"
        md += "\n"

    if commands:
        md += "### Commands\n\n"
        for cmd in commands:
            md += f"- `{cmd}`\n"
        md += "\n"

    if capabilities:
        md += "## Capabilities\n\n"
        for cap in capabilities:
            md += f"- `{cap}`\n"
        md += "\n"

    if config_section:
        md += "## Configuration\n\n"
        required = config_section.get("required", [])
        if required:
            md += "### Required\n\n"
            for key in required:
                md += f"- `{key}`\n"
            md += "\n"

    if deps:
        md += "## Dependencies\n\n"
        pip = deps.get("pip", [])
        npm = deps.get("npm", [])
        skill_deps = deps.get("skills", [])
        if pip:
            md += "### Python (pip)\n\n"
            for d in pip:
                md += f"- `{d}`\n"
            md += "\n"
        if npm:
            md += "### Node.js (npm)\n\n"
            for d in npm:
                md += f"- `{d}`\n"
            md += "\n"
        if skill_deps:
            md += "### Skills\n\n"
            for d in skill_deps:
                md += f"- `{d}`\n"
            md += "\n"

    if perms:
        md += "## Permissions\n\n"
        md += "| Resource | Actions |\n"
        md += "|----------|---------|\n"
        for perm in perms:
            actions = ", ".join(perm.get("actions", []))
            md += f"| `{perm['resource']}` | {actions} |\n"
        md += "\n"

    if lifecycle:
        md += "## Lifecycle Hooks\n\n"
        for hook, script in lifecycle.items():
            md += f"- **{hook}**: `{script}`\n"
        md += "\n"

    md += "---\n\n"
    md += "_Generated by Agent Skills Framework SDK v0.1.0_"

    if output_path:
        Path(output_path).write_text(md, encoding="utf-8")

    return md


def generate_skill_doc(manifest_path: str | Path, format: str = "markdown", output_path: str | Path | None = None) -> str:
    manifest = load_manifest(manifest_path)
    name = manifest["name"]
    version = manifest["version"]
    runtime = manifest["runtime"]

    if format == "markdown":
        return generate_markdown_integration(manifest_path, output_path)

    if format == "json":
        result = {
            "name": name,
            "version": version,
            "runtime": runtime,
            "id": manifest.get("id", ""),
            "description": manifest.get("description", ""),
            "entry": manifest.get("entry", ""),
            "triggers": manifest.get("triggers", {}),
            "capabilities": manifest.get("capabilities", []),
            "config": manifest.get("config", {}),
            "dependencies": manifest.get("dependencies", {}),
            "permissions": manifest.get("permissions", []),
            "lifecycle": manifest.get("lifecycle", {}),
        }
        import json
        text = json.dumps(result, indent=2)
        if output_path:
            Path(output_path).write_text(text, encoding="utf-8")
        return text

    raise ValueError(f"Unsupported format: {format}")
